spring:
  datasource:
#    url: jdbc:mysql://viaduct.proxy.rlwy.net:48697/myblog
#    username: root
#    password: KpOZlzLhKNdNgAdgMNVBobMJcyEZpjJo
  jpa:
    show-sql: false
app:
  oauth2:
    #    # After successfully authenticating with the OAuth2 Provider,
    #    # we'll be generating an auth token for the user and sending the token to the
    #    # redirectUri mentioned by the client in the /oauth2/authorize request.
    #    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - https://myblog-3x6hvxwah-nemisolvs-projects.vercel.app/oauth2/redirect


